version: '3.7'

services:
  web:
    build: .
    ports:
      - 5000:5000
    environment: 
      - FLASK_ENV=production
      - SECRET_KEY=123
    volumes:
      - ~/Data/post_filer/storage:/app/storage
      - ~/Data/post_filer/details:/app/data/details
      - ~/Data/post_filer/uploads:/app/uploads